import type { Metadata } from "next";
import WebLayout from "@components/container/layout";

import "@styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` font-primary  antialiased`}
      >
        <WebLayout>{children}</WebLayout>
      </body>
    </html>
  );
}
